name: sehatyab
description: "FYP project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.3.0+2
  http: ^1.2.1
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0
  image: ^4.2.0
  camera: ^0.10.0+3
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  #  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.0.0

  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.3
  #  webview_flutter: ^4.8.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.2
  animations: ^2.0.11
  flutter_screenutil: ^5.3.1
  equatable: ^2.0.7
  provider: ^6.0.3
  google_generative_ai: ^0.4.6
  get: ^4.6.6
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.10
  flutter_emoji: ^2.5.1
  universal_html: ^2.2.1
  file_picker: ^10.1.2
  hive: ^2.2.3
  flutter_markdown: ^0.6.18

  #  agora_rtc_engine: ^6.5.0
  flutter_colorpicker: ^1.1.0
  firebase_messaging: ^15.2.4
  geolocator: ^9.0.0
  geocoding: ^2.1.0
  googleapis_auth: ^1.6.0
  googleapis: ^11.0.0
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.10
  smooth_page_indicator: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.0.7+1
  hive_generator: ^2.0.0
  build_runner: ^2.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sehatyab.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FFFFFF" # Background color
  image: "assets/images/sehatyab.png" # Replace with your actual image filename
  android: true
  ios: true

flutter:
  uses-material-design: true
#  assets:
#    - assets/fonts/Roboto-Regular.ttf
#    - assets/images/sehatyab.png
#    - assets/images/google_logo.png
    # Add more images here
    # - images/image1.png
    # - images/image2.jpg
    # - assets/images/another_image.png